apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  tolerations:
  - key: "disktype"
    operator: "Equal"
    value: "ssd"
    effect: "Execute"
    tolerationSeconds: 3600
  containers:
  - name: my-container
    image: nginx
